#!/bin/bash

MODULE_HTML=$1
ENV=$2
MODULE_ID=$3

if [ "${ENV}" == "" ] ; then
    ENV=glitch
fi

source  ../.env.$ENV.local

SERVER_URL=${SERVER_URL} ruby create_module2.rb $MODULE_HTML $VUE_APP_PARSE_APP_ID $PARSE_MASTER_KEY $MODULE_ID
